permission/luffy_permission-权限管理终版/luffy_permission/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rbac import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls')),
    url(r'^rbac/', include('rbac.urls',namespace='rbac')),
    url(r'^xxx/', views.xxx,name='xxx'),
]
# reverse('rbac:别名')

permission/luffy_permission-权限管理终版/rbac/urls.py
from django.conf.urls import url,include
from rbac import views

urlpatterns = [
    # /rbac/role/list

    url(r'^role/list/', views.role_list,name='role_list'),
    url(r'^role/add/', views.role_add_edit,name='role_add'),
    url(r'^role/edit/(\d+)/', views.role_add_edit,name='role_edit'),
    url(r'^role/del/(\d+)/', views.role_del,name='role_del'),

    # 菜单相关
    url(r'^menu/list/', views.menu_list,name='menu_list'),
    url(r'^menu/add/', views.menu_add_edit,name='menu_add'),
    url(r'^menu/edit/(\d+)/', views.menu_add_edit,name='menu_edit'),

    #批量操作权限
    url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),
    # 权限分配
    url(r'^distribute/permissions/$', views.distribute_permissions, name='distribute_permissions'),

]

permission/luffy_permission-权限管理终版/web/urls.py
from django.conf.urls import url
from web.views import customer
from web.views import payment
from web.views import auth

# app_name = 'web'

urlpatterns = [



    url(r'^login/$', auth.login,name='login'),
    # url(r'^home/$', auth.home),

    url(r'^customer/list/$', customer.customer_list, name='customer_list'),
    url(r'^customer/add/$', customer.customer_add, name='customer_add'),
    url(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit, name='customer_edit'),
    url(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del, name='customer_del'),

    url(r'^payment/list/$', payment.payment_list, name='payment_list'),
    url(r'^payment/add/$', payment.payment_add, name='payment_add'),
    url(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit, name='payment_edit'),
    url(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del, name='payment_del'),
    url(r'^nashui/$', payment.nashui,name='nashui'),



]

permission/luffy_permission-权限管理终版/rbac/models.py
from django.db import models

# Create your models here.

class Menu(models.Model):
    """
    一级菜单表
    """
    title = models.CharField(max_length=32,verbose_name='菜单名称')  #财务管理
    weight = models.IntegerField(default=100,verbose_name='权重')
    icon = models.CharField(max_length=32, null=True, blank=True, verbose_name='图标')
    def __str__(self):
        return self.title

class UserInfo(models.Model):

    username = models.CharField(max_length=32)
    password = models.CharField(max_length=32)

    roles = models.ManyToManyField('Role')

    def __str__(self):
        return self.username

class Role(models.Model):

    role_name = models.CharField(max_length=16)
    permissions = models.ManyToManyField('Permission')

    def __str__(self):
        return self.role_name

class Permission(models.Model):

    url = models.CharField(max_length=1200)  #/customers/
    title = models.CharField(max_length=32)  # 客户展示
    # is_menu = models.BooleanField(default=False)  #通过这个字段判断这条权限是否是左侧菜单权限
    menu = models.ForeignKey('Menu',null=True,blank=True)  #
    parent = models.ForeignKey('self',null=True,blank=True)
    url_name = models.CharField(max_length=32,null=True,blank=True)
    icon = models.CharField(max_length=32,null=True,blank=True)  #菜单图标


    def __str__(self):
        return self.title

permission/luffy_permission-权限管理终版/rbac/serve/routes.py
from django.conf import settings
from django.utils.module_loading import import_string
from django.urls import RegexURLResolver, RegexURLPattern
from collections import OrderedDict


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    '''

    :param pre_namespace:  None   'rbac'
    :param pre_url:   '/'   '/^rbac/'
    :param urlpatterns:
            [
            # /rbac/role/list

            url(r'^role/list/', views.role_list,name='role_list'),
            url(r'^role/add/', views.role_add_edit,name='role_add'),
            url(r'^role/edit/(\d+)/', views.role_add_edit,name='role_edit'),
            url(r'^role/del/(\d+)/', views.role_del,name='role_del'),

        # 菜单相关
        url(r'^menu/list/', views.menu_list,name='menu_list'),
        url(r'^menu/add/', views.menu_add_edit,name='menu_add'),
        url(r'^menu/edit/(\d+)/', views.menu_add_edit,name='menu_edit'),

        #批量操作权限
        url(r'^multi/permissions/$', views.multi_permissions, name='multi_permissions'),

        ]
        [

            url(r'^', include('web.urls')),
            url(r'^rbac/', include('rbac.urls',namespace='rbac')),
            url(r'^xxx/', views.xxx,name='xxx'),

        ]
    :param url_ordered_dict:   {} {}
    :return:
    '''

    for item in urlpatterns:
        if isinstance(item, RegexURLResolver):
            if pre_namespace:
                if item.namespace:
                    namespace = "%s:%s" % (pre_namespace, item.namespace,)
                else:
                    namespace = pre_namespace
            else:
                if item.namespace:  #'rbac'
                    namespace = item.namespace
                else:
                    namespace = None
                    # '/^rbac/'
            recursion_urls(namespace, pre_url + item.regex.pattern, item.url_patterns, url_ordered_dict)
        else:

            if pre_namespace:  #'rbac'
                name = "%s:%s" % (pre_namespace, item.name,) #rbac:role_list
            else:
                name = item.name  #'xxx'
            if not item.name:
                raise Exception('URL路由中必须设置name属性')

            url = pre_url + item._regex   #'/xxx/' = '/^^login/$'
            url_ordered_dict[name] = {'url_name': name, 'url': url.replace('^', '').replace('$', '')}



            # reverse('login') -- '/login/'
            # {'login':{'name':'login','url':'/login/'},{'rbac:role_list':{'name':'rbac:role_list',url:'/rbac/role/list/'}}}


def get_all_url_dict(ignore_namespace_list=None):
    """
    获取路由中
    :return:
    """
    ignore_list = ignore_namespace_list or [] #短路操作 ['admin',]
    url_ordered_dict = OrderedDict()  #有序字典,最终要使用的字典数据


    md = import_string(settings.ROOT_URLCONF)
    # md = import_string('luffy_permission.urls')

    urlpatterns = []
    '''
        [
            
            url(r'^', include('web.urls')),
            url(r'^rbac/', include('rbac.urls',namespace='rbac')),
            url(r'^xxx/', views.xxx,name='xxx'),
            
        ]
    '''

    '''
        [
            url(r'^admin/', admin.site.urls),
            url(r'^', include('web.urls')),
            url(r'^rbac/', include('rbac.urls',namespace='rbac')),
            url(r'^xxx/', views.xxx,name='xxx'),
        ]
        [<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>,
         <RegexURLResolver <module 'web.urls' from 'D:\\26crm_project\\luffy_permission-最初板\\web\\urls.py'> (None:None) ^>, 
         <RegexURLResolver <module 'rbac.urls' from 'D:\\26crm_project\\luffy_permission-最初板\\rbac\\urls.py'> (None:rbac) ^rbac/>
         <RegexURLPattern xxx ^xxx/>
         ]
        
    '''
    print(md.urlpatterns)
    for item in md.urlpatterns:
        if isinstance(item, RegexURLResolver) and item.namespace in ignore_list:
            continue
        urlpatterns.append(item)

    recursion_urls(None, "/", urlpatterns, url_ordered_dict)
    return url_ordered_dict

permission/luffy_permission-权限管理终版/rbac/views.py
from django.shortcuts import render,HttpResponse,redirect
from rbac import models
from django import forms
from django.utils.safestring import mark_safe
from rbac.serve.icons import icon_list

from rbac.serve.routes import get_all_url_dict

class RoleModelForm(forms.ModelForm):
    class Meta:
        model=models.Role
        fields = '__all__'
        exclude = ['permissions',]

        labels = {
            'role_name':'角色',
        }
        widgets = {
            'role_name':forms.TextInput(attrs={'class':'form-control'})
        }

class MenuModelForm(forms.ModelForm):
    class Meta:
        model=models.Menu
        fields = '__all__'

        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'weight':forms.TextInput(attrs={'class':'form-control'}),
            'icon':forms.RadioSelect(choices=[(i[0],mark_safe(i[1])) for i in icon_list]),
        }


def role_list(request):

    role_lists = models.Role.objects.all()

    return render(request,'rbac/role_list.html',{'role_lists':role_lists})


def role_add_edit(request,rid=None):
    role_objs = models.Role.objects.filter(id=rid).first()
    if request.method == 'GET':
        form = RoleModelForm(instance=role_objs)
        return render(request, 'rbac/role_add.html', {'form': form})
    else:
        form = RoleModelForm(request.POST,instance=role_objs)
        if form.is_valid():
            form.save()
            return redirect('rbac:role_list')
        else:
            return render(request, 'rbac/role_add.html', {'form': form})


# def role_edit(request,rid):
#     role_lists = models.Role.objects.all()
#
#     return render(request, 'rbac/role_list.html', {'role_lists': role_lists})


def role_del(request,rid):
    models.Role.objects.filter(id=rid).delete()
    return redirect('rbac:role_list')


from django.db.models import Q
def menu_list(request):

    menu_lists = models.Menu.objects.all()
    # mid = request.GET.get('mid',0) #字符串类型
    mid = request.GET.get('mid') #字符串类型
    if mid:
        permissions_list = models.Permission.objects.filter(Q(menu_id=mid)|Q(parent__menu_id=mid))
    else:
        permissions_list = models.Permission.objects.all()
    return render(request,'rbac/menu_list.html',{'menu_lists':menu_lists,'permissions_list':permissions_list,'mid':mid})

def menu_add_edit(request,mid=None):
    menu_obj = models.Menu.objects.filter(id=mid).first()
    if request.method == 'GET':
        form = MenuModelForm(instance=menu_obj)
        return render(request,'rbac/menu_add.html',{'form':form})

    else:
        form = MenuModelForm(request.POST,instance=menu_obj)
        if form.is_valid():
            form.save()
            return redirect('rbac:menu_list')
        else:
            return render(request, 'rbac/menu_add.html', {'form': form})

from django.forms import modelformset_factory,formset_factory
from rbac.myform import MultiPermissionForm

def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """

    post_type = request.GET.get('type')  #add

    # 更新和编辑用的
    FormSet = modelformset_factory(models.Permission, MultiPermissionForm, extra=0)


    # 增加用的
    AddFormSet = formset_factory(MultiPermissionForm, extra=0)

    # 获取数据库中现有的所有权限数据
    permissions = models.Permission.objects.all()

    # 获取项目的路由系统中所有URL
    router_dict = get_all_url_dict(ignore_namespace_list=['admin', ])
    #{'':{'name':'','url'}}

    # 数据库中的所有权限的别名
    permissions_name_set = set([i.url_name for i in permissions])

    # 路由系统中的所有权限的别名
    router_name_set = set(router_dict.keys())



    if request.method == 'POST' and post_type == 'add':
        add_formset = AddFormSet(request.POST)
        if add_formset.is_valid():
            print(add_formset.cleaned_data)
            permission_obj_list = [models.Permission(**i) for i in add_formset.cleaned_data]

            query_list = models.Permission.objects.bulk_create(permission_obj_list)

            for i in query_list:
                permissions_name_set.add(i.url_name)

    add_name_set = router_name_set - permissions_name_set  #要新增的那些别名
    add_formset = AddFormSet(initial=[row for name, row in router_dict.items() if name in add_name_set])  #{'url_name':'','url'}
    # {'':{'name':'','url'}}

    del_name_set = permissions_name_set - router_name_set
    del_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=del_name_set))

    update_name_set = permissions_name_set & router_name_set

    update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    if request.method == 'POST' and post_type == 'update':
        update_formset = FormSet(request.POST)
        if update_formset.is_valid():
            update_formset.save()
            update_formset = FormSet(queryset=models.Permission.objects.filter(url_name__in=update_name_set))

    return render(
        request,
        'rbac/multi_permissions.html',
        {
            'del_formset': del_formset,
            'update_formset': update_formset,
            'add_formset': add_formset,
        }
    )



def xxx(request):
    return HttpResponse('xxx')


def distribute_permissions(request):
    """
    分配权限
    :param request:
    :return:
    """

    uid = request.GET.get('uid')
    rid = request.GET.get('rid')

    if request.method == 'POST' and request.POST.get('postType') == 'role':
        user = models.UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')  # 1  2
                                              # 1  3
        user.roles.set(request.POST.getlist('roles'))  #[2,3]

    if request.method == 'POST' and request.POST.get('postType') == 'permission' and rid:
        role = models.Role.objects.filter(id=rid).first()
        if not role:
            return HttpResponse('角色不存在')
        role.permissions.set(request.POST.getlist('permissions'))

    # 所有用户
    user_list = models.UserInfo.objects.all()
    user_has_roles = models.UserInfo.objects.filter(id=uid).values('id', 'roles')

    '''
        {}
    
    '''
    # print('xxxxxxx',user_list)
    # print(user_has_roles)

    user_has_roles_dict = {item['roles']: None for item in user_has_roles}
    # {'角色id':None,}

    """
    用户拥有的角色id
    user_has_roles_dict = { 角色id：None }
    """

    role_list = models.Role.objects.all()
    # print('rrrrr',role_list)
    if rid:
        role_has_permissions = models.Role.objects.filter(id=rid).values('id', 'permissions')
    elif uid and not rid:
        user = models.UserInfo.objects.filter(id=uid).first()
        if not user:
            return HttpResponse('用户不存在')
        role_has_permissions = user.roles.values('id', 'permissions')

    else:
        role_has_permissions = []

    print('kkkkkk', role_has_permissions)
    '''
        <QuerySet [{'id': 4, 'permissions': 1}, {'id': 4, 'permissions': 2}, {'id': 4, 'permissions': 3}, {'id': 4, 'permissions': 4}, {'id': 4, 'permissions': 5}, {'id': 4, 'permissions': 6}, {'id': 4, 'permissions': 7}, {'id': 4, 'permissions': 8}, {'id': 4, 'permissions': 9}, {'id': 4, 'permissions': 10}, {'id': 4, 'permissions': 11}, {'id': 4, 'permissions': 12}, {'id': 4, 'permissions': 13}, {'id': 4, 'permissions': 14}, {'id': 4, 'permissions': 15}, {'id': 4, 'permissions': 16}]>
    
    '''
    role_has_permissions_dict = {item['permissions']: None for item in role_has_permissions}

    '''
        {1:None,2:None}
        if 3 in {1:None,2:None}
    '''


    """
    角色拥有的权限id
    role_has_permissions_dict = { 权限id：None }
    """

    all_menu_list = []
    '''
        [
            {'id':1,'title':'业务管理','children':[
                
                {'id':1,title:'客户展示','menu_id':1,'children':[
                    {'id':2,'title':'客户添加','parent_id':1}
                ]}
            
            ]},
            {'id':2,'title':'财务管理','children':[
                {'id':5,title:'缴费展示','menu_id':2,'children':[]}
            ]},
            {'id': None, 'title': '其他', 'children': [
                {'id':9,'title':'嘻嘻嘻',parent_id:None}
            ]}
        ]
        
    '''

    queryset = models.Menu.objects.values('id', 'title')
    '''
        queryset<[{'id':1,'title':'业务管理','children':[]},]>
    '''
    menu_dict = {}
    '''
        {
            1:{'id':1,'title':'业务管理','children':[
            
                {'id':1,title:'客户展示','menu_id':1,'children':[]}
            ]},
            2:{'id':2,'title':'财务管理','children':[
                {'id':5,title:'缴费展示','menu_id':2,'children':[]}
            ]},
            None:{'id': None, 'title': '其他', 'children': [
                {'id':9,'title':'嘻嘻嘻',parent_id:None}
            ]},
        }
    '''

    for item in queryset:
        item['children'] = []  # 放二级菜单，父权限
        menu_dict[item['id']] = item
        all_menu_list.append(item)

    other = {'id': None, 'title': '其他', 'children': []}
    all_menu_list.append(other)
    menu_dict[None] = other

    root_permission = models.Permission.objects.filter(menu__isnull=False).values('id', 'title', 'menu_id') #二级菜单权限
    '''
        queryset<[{'id':1,title:'客户展示','menu_id':1,'children':[]},]>
    '''
    root_permission_dict = {}
    '''
        {
            二级菜单权限id
            1:{'id':1,title:'客户展示','menu_id':1,'children':[
                {'id':2,'title':'客户添加','parent_id':1}
            ]},
            5:{'id':5,title:'缴费展示','menu_id':2,'children':[]},
        }
    '''

    for per in root_permission:
        per['children'] = []  # 放子权限
        nid = per['id']  #二级菜单权限id
        menu_id = per['menu_id']  # 一级菜单权限id
        root_permission_dict[nid] = per
        menu_dict[menu_id]['children'].append(per)

    node_permission = models.Permission.objects.filter(menu__isnull=True).values('id', 'title', 'parent_id') #二级菜单子权限
    '''
        queryset<[{'id':2,'title':'客户添加','parent_id':1},{'id':9,'title':'嘻嘻嘻',parent_id:None}]>
    '''
    for per in node_permission:
        pid = per['parent_id']

permission/luffy_permission-权限管理终版/rbac/templates/rbac/bread_crumb.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for foo in bread_crumb %}
    {% if forloop.last %}
    <li class="active">{{ foo.title }}</li>
    {% else %}
    <li class="active"><a href="{{ foo.url }}">{{ foo.title }}</a></li>
    {% endif %}


{% endfor %}
</body>
</html>

permission/luffy_permission-权限管理终版/rbac/templates/rbac/distribute_permissions.html
{% extends 'layout.html' %}
{% load mytags %}
{% block css %}
    <style>
        .user-area ul {
            padding-left: 20px;
        }

        .user-area li {
            cursor: pointer;
            padding: 2px 0;
        }

        .user-area li a {
            display: block;
        }

        .user-area li.active {
            font-weight: bold;
            color: red;
        }

        .user-area li.active a {
            color: red;
        }

        .role-area tr td a {
            display: block;
        }

        .role-area tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        .permission-area tr.root {
            background-color: #f1f7fd;
            cursor: pointer;
        }

        .permission-area tr.root td i {
            margin: 3px;
        }

        .permission-area .node {

        }

        .permission-area .node input[type='checkbox'] {
            margin: 0 5px;
        }

        .permission-area .node .parent {
            padding: 5px 0;
        }

        .permission-area .node label {
            font-weight: normal;
            margin-bottom: 0;
            font-size: 12px;
        }

        .permission-area .node .children {
            padding: 0 0 0 20px;
        }

        .permission-area .node .children .child {
            display: inline-block;
            margin: 2px 5px;
        }

        table {
            font-size: 12px;
        }

        .panel-body {
            font-size: 12px;
        }

        .panel-body .form-control {
            font-size: 12px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="luffy-container">
        <div class="col-md-3 user-area">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <i class="fa fa-address-book-o" aria-hidden="true"></i> 用户信息
                </div>

                <div class="panel-body">
                    <ul>
                        {% for user in user_list %}

                            <li class= {% if user.id|safe == uid %} "active" {% endif %}>
                                <a href="?uid={{ user.id }}">{{ user.username }}</a></li>

                        {% endfor %}
                    </ul>
                </div>

            </div>
        </div>

        <div class="col-md-3 role-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="postType" value="role">

                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <i class="fa fa-book" aria-hidden="true"></i> 角色
                        {% if uid %}
                            <button type="submit" class="right btn btn-success btn-xs"
                                    style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body" style="color: #d4d4d4;padding:10px  5px;">
                        提示：点击用户后才能为其分配角色
                    </div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>角色</th>
                            <th>选择</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for role in role_list %}
                            <tr {% if role.id|safe == rid %} class="active"  {% endif %}>

                                <td><a href="?{% gen_role_url request role.id %}">{{ role.role_name }}</a></td>
                                <td>
                                    {% if role.id in user_has_roles_dict %}
                                        <input type="checkbox" name="roles" value="{{ role.id }}" checked/>
                                    {% else %}
                                        <input type="checkbox" name="roles" value="{{ role.id }}"/>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>

                </div>
            </form>
        </div>

        <div class="col-md-6 permission-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="postType" value="permission">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading">
                        <i class="fa fa-sitemap" aria-hidden="true"></i> 权限分配
                        {% if rid %}
                            <button class="right btn btn-success btn-xs" style="padding: 2px 8px;margin: -3px;">
                                <i class="fa fa-save" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body" style="color: #d4d4d4;padding: 10px 5px;">
                        提示：点击角色后，才能为其分配权限。
                    </div>
                    <table class="table">
                        <tbody>
                        {% for item in all_menu_list %}
                            <tr class="root">
                                <td><i class="fa fa-caret-down" aria-hidden="true"></i>{{ item.title }}</td>
                            </tr>
                            <tr class="node">
                                <td>
                                    {% for node in item.children %}
                                        <div class="parent">
                                            {% if node.id in role_has_permissions_dict %}
                                                <input id="permission_{{ node.id }}" name="permissions" value="{{ node.id }}" type="checkbox" checked>
                                            {% else %}
                                                <input id="permission_{{ node.id }}" name="permissions" value="{{ node.id }}" type="checkbox">
                                            {% endif %}
<!-- <input id='permission_二级菜单权限id' name="permissions" value="二级菜单权限id" type="checkbox"> -->

                                            <label for="permission_{{ node.id }}">{{ node.title }}</label>

                                        </div>
                                        <div class="children">
                                            {% for child in node.children %}
                                                <div class="child">
                                                    {% if child.id in role_has_permissions_dict %}
                                                        <input id="permission_{{ child.id }}" name="permissions"
                                                               type="checkbox" value="{{ child.id }}" checked>
                                                    {% else %}
                                                        <input id="permission_{{ child.id }}" name="permissions"
                                                               type="checkbox" value="{{ child.id }}">
                                                    {% endif %}

                                                    <label for="permission_{{ child.id }}">{{ child.title }}</label>
                                                </div>
                                            {% endfor %}
                                        </div>
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>

    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            bindRootPermissionClick();
        });

        function bindRootPermissionClick() {
            $('.permission-area').on('click', '.root', function () {
                var caret = $(this).find('i');
                if (caret.hasClass('fa-caret-right')) {
                    caret.removeClass('fa-caret-right').addClass('fa-caret-down');
                    $(this).next().removeClass('hide');
                } else {
                    caret.removeClass('fa-caret-down').addClass('fa-caret-right');
                    $(this).next().addClass('hide');

                }
            })
        }
    </script>
{% endblock %}

permission/luffy_permission-权限管理终版/rbac/templates/rbac/menu_list.html
{% extends 'layout.html' %}



{% block content %}
<div class="row">

    <div class="col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading"> <i class="fa fa-book"></i>菜单管理 <a style="padding: 2px 2px" href="{% url 'rbac:menu_add' %}" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> 新建</a></div>
          <div class="panel-body">
            <table class="table table-bordered table-hover table-striped menu-body">
                <thead>
                <tr>
                    <th>名称</th>
                    <th>图标</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for menu in menu_lists %}
                <tr class="{% if mid == menu.id|safe %}active{% endif %}">
                    <td><a href="?mid={{ menu.id }}">{{ menu.title }}</a></td>
                    <td><i class="fa {{ menu.icon }}"></i></td>
                    <td>
                        <a href="{% url 'rbac:menu_edit' menu.id %}"><i class="fa fa-edit"></i></a>
                        <a href=""><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
                {% endfor %}

                </tbody>


            </table>

          </div>
        </div>

    </div>

    <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading"> <i class="fa fa-cubes"></i>权限管理
              <a style="padding: 2px 2px" class="btn btn-primary btn-sm pull-right"><i class="fa fa-scissors"></i> 批量操作</a>
              <a style="padding: 2px 2px" class="btn btn-success btn-sm pull-right"><i class="fa fa-plus"></i> 新建</a>

          </div>
          <div class="panel-body">
            <table class="table table-bordered table-hover permission-area2">
                <thead>
                <tr>
                    <th>名称</th>
                    <th>URL</th>
                    <th>URL别名</th>
                    <th>菜单</th>
                    <th>所属菜单</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for permissions in permissions_list %}
                <tr class="{% if permissions.menu_id %}parent{% endif %}">
                    <td>
                        {% if permissions.menu_id %}<i class="fa fa-caret-down xx"></i>{% endif %}
                        {{ permissions.title }}</td>
                    <td>{{ permissions.url }}</td>
                    <td>{{ permissions.url_name }}</td>
                    <td>
                        {% if permissions.menu_id %}
                        是
                        {% endif %}
                    </td>

                    <td>{{ permissions.menu.title }}</td>

                    <td>
                        <a href=""><i class="fa fa-edit"></i></a>
                        <a href=""><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
                {% endfor %}

                </tbody>


            </table>

          </div>
        </div>

    </div>

</div>

{% endblock %}

permission/luffy_permission-权限管理终版/rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}



{% block content %}

    <div class="luffy-container">

        <div class="btn-group" style="margin: 5px 0">

            <a class="btn btn-default" href="{% url 'rbac:role_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加角色
            </a>
        </div>


        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>角色</th>

                <th>选项</th>

            </tr>
            </thead>
            <tbody>
            {% for row in role_lists %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.role_name }}</td>


                    <td>

                        <a style="color: #333333;" href="{% url 'rbac:role_edit' row.id %} ">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>


                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' row.id %}"><i class="fa fa-trash-o"></i></a>

                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}