crm/app01/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^home/$', views.home, name='home'),
    url(r'^customer/$', views.Customer.as_view(), name='customer'),
    url(r'^mycustomer/$', views.Customer.as_view(), name='mycustomer'),
    url(r'^customer/add/$', views.CustomerAddEdit.as_view(), name='customer_add'),
    url(r'^customer/edit/(\d+)/$', views.CustomerAddEdit.as_view(), name='customer_edit'),
    url(r'^customer/del/(\d+)/$', views.customerDel, name='customer_del'),
    url(r'^records/follow/$', views.FollowRecord.as_view(), name='follow_records'),
    url(r'^records/follow/add/$', views.FollowRecordAddEdit.as_view(), name='follow_records_add'),
    url(r'^records/follow/edit/(\d+)/$', views.FollowRecordAddEdit.as_view(), name='follow_records_edit'),
    url(r'^records/follow/del/(\d+)/$', views.followRecordDel, name='follow_records_del'),
    url(r'^enrollment/$', views.Enrollment.as_view(), name='enrollment'),
    url(r'^enrollment/add/$', views.EnrollmentAddEdit.as_view(), name='enrollment_add'),
    url(r'^enrollment/edit/(\d+)/$', views.EnrollmentAddEdit.as_view(), name='enrollment_edit'),
    url(r'^enrollment/del/(\d+)/$', views.enrollmentDel, name='enrollment_del'),
    url(r'^records/course/$', views.CourseRecord.as_view(), name='course_records'),
    url(r'^records/course/add/$', views.CourseRecordAddEdit.as_view(), name='course_records_add'),
    url(r'^records/course/edit/(\d+)/$', views.CourseRecordAddEdit.as_view(), name='course_records_edit'),
    url(r'^records/course/del/(\d+)/$', views.courseRecordDel, name='course_records_del'),
    url(r'^records/study/(\d+)/$', views.StudyRecord.as_view(), name='study_records'),
]

crm/crm/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include("app01.urls", namespace="app01")),
]

crm/app01/models.py
from django.db import models
from multiselectfield import MultiSelectField

# Create your models here.
course_choices = (('LinuxL', 'Linux中高级'),
                  ('PythonFullStack', 'Python高级全栈开发'),)

class_type_choices = (('fulltime', '脱产班',),
                      ('online', '网络班'),
                      ('weekend', '周末班',),)

source_type = (('qq', "qq群"),
               ('referral', "内部转介绍"),
               ('website', "官方网站"),
               ('baidu_ads', "百度推广"),
               ('office_direct', "直接上门"),
               ('WoM', "口碑"),
               ('public_class', "公开课"),
               ('website_luffy', "路飞官网"),
               ('others', "其它"),)

enroll_status_choices = (('signed', "已报名"),
                         ('unregistered', "未报名"),
                         ('studying', '学习中'),
                         ('paid_in_full', "学费已交齐"))

seek_status_choices = (('A', '近期无报名计划'), ('B', '1个月内报名'), ('C', '2周内报名'), ('D', '1周内报名'),
                       ('E', '定金'), ('F', '到班'), ('G', '全款'), ('H', '无效'))
pay_type_choices = (('deposit', "订金/报名费"),
                    ('tuition', "学费"),
                    ('transfer', "转班"),
                    ('dropout', "退学"),
                    ('refund', "退款"),)

attendance_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('absence', "缺勤"),
                      ('leave_early', "早退"),)

score_choices = ((100, 'A+'),
                 (90, 'A'),
                 (85, 'B+'),
                 (80, 'B'),
                 (70, 'B-'),
                 (60, 'C+'),
                 (50, 'C'),
                 (40, 'C-'),
                 (0, ' D'),
                 (-1, 'N/A'),
                 (-100, 'COPY'),
                 (-1000, 'FAIL'),)


class UserInfo(models.Model):
    username = models.CharField(max_length=18)
    password = models.CharField(max_length=32)
    telephone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.username


class Customer(models.Model):
    """
    客户表（最开始的时候大家都是客户，销售就不停的撩你，你还没交钱就是个客户）
    """
    qq = models.CharField(verbose_name='QQ', max_length=64, unique=True, help_text='QQ号必须唯一')
    qq_name = models.CharField('QQ昵称', max_length=64, blank=True, null=True)
    name = models.CharField('姓名', max_length=32, help_text='学员报名后，请改为真实姓名')  # 可为空，有些人就不愿意给自己的真实姓名
    sex_type = (('male', '男'), ('female', '女'))
    sex = models.CharField("性别", choices=sex_type, max_length=16, default='male', blank=True,
                           null=True)  # 存的是male或者female，字符串
    birthday = models.DateField('出生日期', default=None, help_text="格式yyyy-mm-dd", blank=True, null=True)
    phone = models.CharField('手机号', blank=True, null=True, max_length=11)  # 手机号改成字符串的，不然不好搜索
    source = models.CharField('客户来源', max_length=64, choices=source_type, default='qq')
    introduce_from = models.ForeignKey('self', verbose_name="转介绍自学员", blank=True, null=True,
                                       on_delete=models.CASCADE)  # self指的就是自己这个表，和下面写法是一样的效果,自关联
    course = MultiSelectField("咨询课程", choices=course_choices)  # 多选，并且存成一个列表的格式,通过modelform来用的时候，会成为一个多选框
    class_type = models.CharField("班级类型", max_length=64, choices=class_type_choices, default='fulltime')
    customer_note = models.TextField("客户备注", blank=True, null=True, )
    status = models.CharField("状态", choices=enroll_status_choices, max_length=64, default="unregistered",
                              help_text="选择客户此时的状态")  # help_text这种参数基本都是针对admin应用里面用的
    date = models.DateTimeField("咨询日期", auto_now_add=True)  # 这个没啥用昂，我问销售，销售说是为了一周年的时候给客户发一个祝福信息啥的
    last_consult_date = models.DateField("最后跟进日期", auto_now_add=True)  # 考核销售的跟进情况，如果多天没有跟进，会影响销售的绩效等
    next_date = models.DateField("预计再次跟进时间", blank=True, null=True)  # 销售自己大概记录一下自己下一次会什么时候跟进，也没啥用
    # 用户表中存放的是自己公司的所有员工。
    # consultant = models.ForeignKey('Userinfo', verbose_name="销售", related_name='customers', blank=True, null=True,
    # on_delete=models.CASCADE)
    # related_name='customers'替换的就是反向查询时,小写表名_set
    consultant = models.ForeignKey('UserInfo', verbose_name="销售", blank=True, null=True, on_delete=models.CASCADE)
    # 一个客户可以报多个班，报个脱产班，再报个周末班等，所以是多对多。
    class_list = models.ManyToManyField('ClassList', verbose_name="已报班级", blank=True)
    delete_status = models.BooleanField(default=False)

    class Meta:
        ordering = ['id', ]
        verbose_name = '客户信息表'
        verbose_name_plural = '客户信息表'

    def __str__(self):
        return self.name + ":" + self.qq


class Campuses(models.Model):
    """
    校区表
    """
    name = models.CharField(verbose_name='校区', max_length=64)
    address = models.CharField(verbose_name='详细地址', max_length=512, blank=True, null=True)

    def __str__(self):
        return self.name


class ClassList(models.Model):
    """
    班级表
    """
    course = models.CharField("课程名称", max_length=64, choices=course_choices)
    semester = models.IntegerField("学期")
    campuses = models.ForeignKey('Campuses', verbose_name="校区", on_delete=models.CASCADE)
    price = models.IntegerField("学费", default=20000)
    memo = models.CharField('说明', blank=True, null=True, max_length=100)
    start_date = models.DateField("开班日期")
    graduate_date = models.DateField("结业日期", blank=True, null=True)  # 不一定什么时候结业，哈哈，所以可为空
    # contract = models.ForeignKey('ContractTemplate', verbose_name="选择合同模版", blank=True, null=True,on_delete=models.CASCADE)
    teachers = models.ManyToManyField('UserInfo', verbose_name="老师")
    class_type = models.CharField(choices=class_type_choices, max_length=64, verbose_name='班级类型', blank=True, null=True)

    class Meta:
        unique_together = ("course", "semester", 'campuses')

    def __str__(self):
        return "{}{}({})".format(self.get_course_display(), self.semester, self.campuses)


class ConsultRecord(models.Model):
    """
    跟进记录表
    """
    customer = models.ForeignKey('Customer', verbose_name="所咨询客户", related_name="consult_message")
    note = models.TextField(verbose_name="跟进内容")
    status = models.CharField("跟进状态", max_length=8, choices=seek_status_choices, help_text="选择客户此时的状态")
    consultant = models.ForeignKey("UserInfo", verbose_name="跟进人", related_name='records')
    date = models.DateTimeField("跟进日期", auto_now_add=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)


class Enrollment(models.Model):
    """
    报名表
    """
    why_us = models.TextField("为什么报名", max_length=1024, default=None, blank=True, null=True)
    your_expectation = models.TextField("学完想达到的具体期望", max_length=1024, blank=True, null=True)
    audit_status = ((1, "审核通过"), (2, "审核未通过"))
    contract_approved = models.IntegerField("审批通过", help_text="在审阅完学员的资料无误后勾选此项,合同即生效", choices=audit_status)
    enrolled_date = models.DateTimeField(auto_now_add=True, verbose_name="报名日期")
    memo = models.TextField('备注', blank=True, null=True)
    delete_status = models.BooleanField(verbose_name='删除状态', default=False)
    customer = models.ForeignKey('Customer', verbose_name='客户名称')
    school = models.ForeignKey('Campuses')
    enrolment_class = models.ForeignKey("ClassList", verbose_name="所报班级")

    class Meta:
        unique_together = ('enrolment_class', 'customer')

    def __str__(self):
        return self.customer.name


class CourseRecord(models.Model):
    """课程记录表"""
    day_num = models.IntegerField("节次", help_text="此处填写第几节课或第几天课程...,必须为数字")
    date = models.DateField(auto_now_add=True, verbose_name="上课日期")
    course_title = models.CharField('本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField('本节课程内容', max_length=300, blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField('本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField('作业描述', max_length=500, blank=True, null=True)
    scoring_point = models.TextField('得分点', max_length=300, blank=True, null=True)

    re_class = models.ForeignKey('ClassList', verbose_name="班级")
    teacher = models.ForeignKey('UserInfo', verbose_name="讲师")

    class Meta:
        unique_together = ('re_class', 'day_num')

    def __str__(self):
        return str(self.day_num)


class StudyRecord(models.Model):
    """
    学习记录
    """
    attendance = models.CharField("考勤", choices=attendance_choices, default="checked", max_length=64)
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(max_length=255, verbose_name='作业批语', blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True)
    note = models.CharField("备注", max_length=255, blank=True, null=True)
    homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)
    course_record = models.ForeignKey('CourseRecord', verbose_name="某节课程")
    student = models.ForeignKey('Customer', verbose_name="学员")

    class Meta:
        unique_together = ('course_record', 'student')

    def __str__(self):
        return self.student.name + ':' + str(self.course_record.day_num)

crm/templates/sales/course_addedit.html
{% extends "page_template.html" %}

{% block title %}
    {% if cid %}
        编辑课程信息页面
    {% else %}
        添加课程信息页面
    {% endif %}
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in fields %}
            <div class="form-group col-md-6">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">保存</button>
    </form>
{% endblock %}

crm/templates/sales/course_records.html
{% extends "page_template.html" %}

{% load mytags %}

{% block title %}
    课程记录
{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
        <div class="panel-body">
            <a href="{% resolve_url request 'app01:course_records_add' %}" class="float-left">
                <button class="btn btn-primary">添加课程信息</button>
            </a>
            {#            <form>#}
            {#                <div class="input-group mb-3 col-md-4 float-right">#}
            {#                    <div class="input-group-prepend">#}
            {#                        <select class="custom-select" id="inputGroupSelect01" name="action">#}
            {#                            <option value='' selected>关键字</option>#}
            {#                            <option value="qq__contains">QQ</option>#}
            {#                            <option value="name__contains">姓名</option>#}
            {#                        </select>#}
            {#                    </div>#}
            {#                    <input type="text" class="form-control" aria-label="Text input with dropdown button"#}
            {#                           placeholder="请输入搜索内容" name="cd">#}
            {#                    <div class="input-group-prepend">#}
            {#                        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">搜索</button>#}
            {#                    </div>#}
            {#                </div>#}
            {#            </form>#}
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3 col-md-4 float-left">
                <div class="input-group-prepend">
                    <select class="custom-select" id="inputGroupSelect01" name="bluk_action">
                        <option value="bluk_create_records">批量添加学习记录</option>
                    </select>
                </div>
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary go" type="button" id="button-addon1">批量操作</button>
                </div>
            </div>

            <!-- Table -->
            <table style="margin-top: 10px" class="table table-striped table-hover">
                <thead class="thead-dark">
                <tr style="text-align: center; vertical-align: middle;">
                    <th>
                        全选 <input type="checkbox" id="checkall">
                    </th>
                    <th>序号</th>
                    <th>节次</th>
                    <th>上课日期</th>
                    <th>本节课程标题</th>
                    <th>本节课程内容</th>
                    <th>班级</th>
                    <th>讲师</th>
                    <th>学习记录</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for record in course_records %}
                    <tr style="text-align: center; vertical-align: middle;">
                        <td>
                            <input type="checkbox" name="cids" value="{{ record.id }}">
                        </td>
                        <td>{% list_number request forloop.counter obj %}</td>
                        <td>{{ record.day_num }}</td>
                        <td>{{ record.date|date:"Y-m-d" }}</td>
                        <td>{{ record.course_title }}</td>
                        <td>{{ record.course_memo }}</td>
                        <td>{{ record.re_class }}</td>
                        <td>{{ record.teacher.username }}</td>
                        <td>
                            <a href="{% url 'app01:study_records' record.id %}">查看学习记录</a>
                        </td>
                        <td>
                            <a href="{% resolve_url request 'app01:course_records_edit' record.id %}" title="编辑"><i
                                    class="fa fa-pencil"></i>&nbsp;</a>|
                            <a href="{% resolve_url request 'app01:course_records_del' record.id course_records|length %}"
                               title="删除"><i class="fa fa-remove"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
    {{ page_html }}

{% endblock %}

{% block script %}
    <script>
        $('#checkall').click(function () {
            if ($(this).prop("checked")) {
                $('[name="cids"]').prop("checked", true)
            } else {
                $('[name="cids"]').prop("checked", false)
            }
        });

        $('.go').click(function () {
            var bluk_action = $('[name="bluk_action"]').val();
            var cids = $('[type="checkbox"]:checked');
            var cid_list = [];
            for (var i = 0; i < cids.length; i++) {
                var cid = cids.eq(i).val();
                cid_list.push(cid)
            }
            {#console.log(cid_list);#}
            $.ajax({
                    url: '',
                    type: 'post',
                    data: {bluk_action: bluk_action, cid_list: JSON.stringify(cid_list), csrfmiddlewaretoken: '{{ csrf_token }}'},
                    success: function (res) {
                        console.log(res);
                        if(res === "1"){
                            alert("添加成功！")
                        }else{
                            alert("添加失败！")
                        }
                    }
                }
            )
        })
    </script>
{% endblock %}

crm/templates/sales/customer_addedit.html
{% extends "page_template.html" %}

{% block title %}
    {% if cid %}
        编辑客户页面
    {% else %}
        添加客户页面
    {% endif %}
{% endblock %}

{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% for field in fields %}
            <div class="form-group col-md-6">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                <span style="color: red">{{ field.errors.0 }}</span>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">保存</button>
    </form>
{% endblock %}

crm/templates/sales/customer_list.html
{% extends "page_template.html" %}

{% load mytags %}

{% block title %}
    {{ request.path|title_name }}
{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
        <div class="panel-body">
            {% if tag == 1 %}
                <a href="{% resolve_url request 'app01:customer_add' %}" class="float-left">
                    <button class="btn btn-primary">添加客户</button>
                </a>
            {% endif %}
            <form>
                <div class="input-group mb-3 col-md-4 float-right">
                    <div class="input-group-prepend">
                        <select class="custom-select" id="inputGroupSelect01" name="action">
                            <option value='' selected>关键字</option>
                            <option value="qq__contains">QQ</option>
                            <option value="name__contains">姓名</option>
                        </select>
                    </div>
                    <input type="text" class="form-control" aria-label="Text input with dropdown button"
                           placeholder="请输入搜索内容" name="cd">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">搜索</button>
                    </div>
                </div>
            </form>
        </div>

        <form method="post">
            {% csrf_token %}
            <div class="input-group mb-3 col-md-4 float-left">
                <div class="input-group-prepend">
                    <select class="custom-select" id="inputGroupSelect01" name="bluk_action">
                        {% if tag == 1 %}
                            <option value="transform_gs">公户转私户</option>
                        {% else %}
                            <option value="transform_sg">私户转公户</option>
                        {% endif %}
                    </select>
                </div>
                <div class="input-group-prepend">
                    <button class="btn btn-outline-secondary go" type="button" id="button-addon1">批量操作</button>
                </div>
            </div>

            <!-- Table -->
            <table style="margin-top: 10px" class="table table-striped table-hover">
                <thead class="thead-dark">
                <tr style="text-align: center; vertical-align: middle;">
                    <th>
                        全选 <input type="checkbox" id="checkall">
                    </th>
                    <th>序号</th>
                    <th>QQ</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>客户来源</th>
                    <th>咨询课程</th>
                    <th>状态</th>
                    {% if tag == 2 %}
                        <th>跟进详情</th>
                    {% endif %}
                    <th>销售</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for customer in customers %}
                    <tr style="text-align: center; vertical-align: middle;">
                        <td>
                            <input type="checkbox" name="cids" value="{{ customer.id }}">
                        </td>
                        <td>{% list_number request forloop.counter obj %}</td>
                        <td>{{ customer.qq }}</td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.get_sex_display }}</td>
                        <td>{{ customer.get_source_display }}</td>
                        <td>{{ customer.get_course_display }}</td>
                        <td>{{ customer.get_status_display }}</td>
                        {% if tag == 2 %}
                            <td>
                                <a href="{% url 'app01:follow_records' %}?cid={{ customer.id }}">详细信息</a>
                            </td>
                        {% endif %}
                        <td>{{ customer.consultant|default:"暂无" }}</td>
                        <td>
                            <a href="{% resolve_url request 'app01:customer_edit' customer.id %}" title="编辑"><i
                                    class="fa fa-pencil"></i>&nbsp;</a>|
                            <a href="{% resolve_url request 'app01:customer_del' customer.id customers|length %}"
                               title="删除"><i class="fa fa-remove"></i></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </form>
    </div>
    {{ page_html }}
{% endblock %}

{% block script %}
    <script>
        $('#checkall').click(function () {
            if ($(this).prop("checked")) {
                $('[name="cids"]').prop("checked", true)
            } else {
                $('[name="cids"]').prop("checked", false)
            }
        });

        $('.go').click(function () {
            var bluk_action = $('[name="bluk_action"]').val();
            var cids = $('[type="checkbox"]:checked');
            var cid_list = [];
            for (var i=0;i<cids.length;i++){
                var cid = cids.eq(i).val();
                cid_list.push(cid);
            }
            console.log(cid_list);
            $.ajax({
                url: '',
                type: 'post',
                data: {bluk_action: bluk_action, cids: JSON.stringify(cid_list), csrfmiddlewaretoken: '{{ csrf_token }}'},
                success: function (res) {
                    console.log(res);
                    if (res.status === 1){
                        alert("操作成功！");
                        location.reload()
                    }
                    else{
                        alert(res.mes);
                        location.reload()
                    }
                }
            })
        });
    </script>
{% endblock %}

crm/templates/sales/enrollment_list.html
{% extends "page_template.html" %}

{% load mytags %}

{% block title %}
    报名信息
{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
        <div class="panel-body">
            <a href="{% resolve_url request 'app01:enrollment_add' %}" class="float-left">
                <button class="btn btn-primary">添加报名信息</button>
            </a>
            <form>
                <div class="input-group mb-3 col-md-4 float-right">
                    <div class="input-group-prepend">
                        <select class="custom-select" id="inputGroupSelect01" name="action">
                            <option value='' selected>关键字</option>
                            <option value="audit_status__contains">审批状态</option>
                            <option value="school__name__contains">校区</option>
                            <option value="enrolment_class__course__contains">所报班级</option>
                        </select>
                    </div>
                    <input type="text" class="form-control" aria-label="Text input with dropdown button"
                           placeholder="请输入搜索内容" name="cd">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">搜索</button>
                    </div>
                </div>
            </form>
        </div>

        {#        <form method="post">#}
        {#            {% csrf_token %}#}
        {#            <div class="input-group mb-3 col-md-4 float-left">#}
        {#                <div class="input-group-prepend">#}
        {#                    <select class="custom-select" id="inputGroupSelect01" name="bluk_action">#}
        {#                        <option value="bluk_delete">批量删除</option>#}
        {#                    </select>#}
        {#                </div>#}
        {#                <div class="input-group-prepend">#}
        {#                    <button class="btn btn-outline-secondary" type="submit" id="button-addon1">批量操作</button>#}
        {#                </div>#}
        {#            </div>#}

        <!-- Table -->
        <table style="margin-top: 10px" class="table table-striped table-hover">
            <thead class="thead-dark">
            <tr style="text-align: center; vertical-align: middle;">
                <th>
                    全选 <input type="checkbox" id="checkall">
                </th>
                <th>序号</th>
                <th>为什么报名</th>
                <th>审批通过</th>
                <th>客户名称</th>
                <th>校区</th>
                <th>所报班级</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for enrollment in enrollments %}
                <tr style="text-align: center; vertical-align: middle;">
                    <td>
                        <input type="checkbox" name="cids" value="{{ enrollment.id }}">
                    </td>
                    <td>{% list_number request forloop.counter obj %}</td>
                    <td>{{ enrollment.why_us }}</td>
                    <td>{{ enrollment.get_contract_approved_display }}</td>
                    <td>{{ enrollment.customer.name }}</td>
                    <td>{{ enrollment.school.name }}</td>
                    <td>{{ enrollment.enrolment_class }}</td>
                    <td>
                        <a href="{% resolve_url request 'app01:enrollment_edit' enrollment.id %}" title="编辑"><i
                                class="fa fa-pencil"></i>&nbsp;</a>|
                        <a href="{% resolve_url request 'app01:enrollment_del' enrollment.id enrollments|length %}"
                           title="删除"><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {#        </form>#}
    </div>
    {{ page_html }}

{% endblock %}

{% block script %}
    <script>
        $('#checkall').click(function () {
            if ($(this).prop("checked")) {
                $('[name="cids"]').prop("checked", true)
            } else {
                $('[name="cids"]').prop("checked", false)
            }
        })
    </script>
{% endblock %}

crm/templates/sales/follow_records.html
{% extends "page_template.html" %}

{% load mytags %}

{% block title %}
    跟进记录
{% endblock %}

{% block content %}

    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"></div>
        <div class="panel-body">
            <a href="{% resolve_url request 'app01:follow_records_add' %}" class="float-left">
                    <button class="btn btn-primary">添加跟进记录</button>
                </a>
            <form>
                <div class="input-group mb-3 col-md-4 float-right">
                    <div class="input-group-prepend">
                        <select class="custom-select" id="inputGroupSelect01" name="action">
                            <option value='' selected>关键字</option>
                            <option value="customer__name__contains">姓名</option>
                            <option value="status__contains">跟进状态</option>
                        </select>
                    </div>
                    <input type="text" class="form-control" aria-label="Text input with dropdown button"
                           placeholder="请输入搜索内容" name="cd">
                    <div class="input-group-prepend">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon1">搜索</button>
                    </div>
                </div>
            </form>
        </div>

        <table style="margin-top: 10px" class="table table-striped table-hover">
            <thead class="thead-dark">
            <tr style="text-align: center; vertical-align: middle;">
                <th>序号</th>
                <th>姓名</th>
                <th>跟进内容</th>
                <th>跟进状态</th>
                <th>跟进日期</th>
                <th>销售</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for record in records %}
                <tr style="text-align: center; vertical-align: middle;">
                    <td>{% list_number request forloop.counter obj %}</td>
                    <td>{{ record.customer.name }}</td>
                    <td>{{ record.note }}</td>
                    <td>{{ record.get_status_display }}</td>
                    <td>{{ record.date|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ record.consultant.username }}</td>
                    <td>
                        <a href="{% resolve_url request 'app01:follow_records_edit' record.id %}" title="编辑"><i class="fa fa-pencil"></i>&nbsp;</a>|
                        <a href="{% resolve_url request 'app01:follow_records_del' record.id records|length %}" title="删除"><i class="fa fa-remove"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {{ page_html }}

{% endblock %}